<div class="space-y-7">
    <section class="admin-hero"><p class="admin-kicker">{{ __('Task detail') }}</p><h1 class="mt-2 text-3xl font-bold">{{ $task->title }}</h1><p class="mt-2 text-sm text-[#626a61]">{{ $task->status->label() }} · {{ $task->priority->label() }}</p></section>
    @if(session('task-saved'))<div role="status" class="rounded-xl bg-[#edf5e5] p-4 text-sm font-semibold text-[#398344]">{{ __('Task saved.') }}</div>@endif
    <div class="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><section class="saas-feature-card p-5 sm:p-6"><form wire:submit="save" class="space-y-4"><flux:input wire:model="title" :label="__('Title')"/><div class="grid gap-4 sm:grid-cols-2"><flux:select wire:model="taskTypeId" :label="__('Type')">@foreach($this->types as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</flux:select><flux:select wire:model="priority" :label="__('Priority')">@foreach(\Andremellow\Tasks\Enums\TaskPriority::cases() as $value)<option value="{{ $value->value }}">{{ $value->label() }}</option>@endforeach</flux:select><flux:input type="date" wire:model="dueDate" :label="__('Due date')"/><flux:select wire:model="status" wire:change="move" :label="__('Status')">@foreach(\Andremellow\Tasks\Enums\TaskStatus::cases() as $value)<option value="{{ $value->value }}">{{ $value->label() }}</option>@endforeach</flux:select></div><div class="flex gap-2"><flux:button type="button" wire:click="$set('preview', false)">{{ __('Edit Markdown') }}</flux:button><flux:button type="button" wire:click="$set('preview', true)">{{ __('Preview') }}</flux:button></div>@if($preview)<div class="prose max-w-none rounded-2xl border p-4">{!! str($description)->markdown(['html_input' => 'strip', 'allow_unsafe_links' => false]) !!}</div>@else<x-tasks::markdown-editor model="description" :value="$description"/>@endif<div class="grid gap-2 sm:grid-cols-2">@foreach($this->tags as $tag)<flux:checkbox wire:model="tagIds" value="{{ $tag->id }}" :label="$tag->name"/>@endforeach</div>@can('update', $task)<flux:button type="submit" variant="primary">{{ __('Save task') }}</flux:button>@endcan</form></section>
        <aside class="space-y-5"><section class="saas-feature-card p-5"><h2 class="font-bold">{{ __('Assignment') }}</h2>@can('assign', $task)<flux:select wire:model="assigneeId" wire:change="assign" :label="__('Assignee')"><option value="">{{ __('Unassigned') }}</option>@if($task->assignee && !$this->assignees->contains('id', $task->assignee_id))<option value="{{ $task->assignee_id }}">{{ $task->assignee->name }} ({{ __('ineligible') }})</option>@endif @foreach($this->assignees as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</flux:select>@else<p class="mt-2 text-sm">{{ $task->assignee?->name ?? __('Unassigned') }}</p>@endcan</section>
        <section class="saas-feature-card p-5"><h2 class="font-bold">{{ __('Attachments') }}</h2><ul class="mt-3 space-y-2">@foreach($this->attachments as $media)<li class="flex items-center justify-between gap-2 text-sm"><a class="truncate text-[#4f7841]" href="{{ route(config('tasks.web.name').'attachments.download', [$task, $media]) }}">{{ $media->name }}</a>@can('manageAttachments', $task)<button type="button" wire:click="removeAttachment({{ $media->id }})" class="text-[#c64242]">{{ __('Remove') }}</button>@endcan</li>@endforeach</ul>@can('manageAttachments', $task)<form wire:submit="upload" class="mt-4 space-y-3"><input type="file" wire:model="uploads" multiple aria-label="{{ __('Add attachments') }}"><p class="text-xs text-[#737a72]">{{ __('Allowed documents and images, up to 10 MB per file.') }}</p><flux:button type="submit">{{ __('Upload') }}</flux:button></form>@endcan</section>
        @can('delete', $task)<flux:button variant="danger" wire:click="delete" wire:confirm="{{ __('Delete this task?') }}">{{ __('Delete task') }}</flux:button>@endcan</aside></div>
    <section class="saas-feature-card p-5"><h2 class="font-bold">{{ __('Change history') }}</h2><ol class="mt-4 space-y-3">@forelse($this->history as $change)<li class="border-l-2 border-[#dce6d2] pl-4 text-sm"><strong>{{ __(str($change->operation)->headline()->toString()) }}</strong><span class="text-[#737a72]"> · {{ $change->actor?->name ?? __('Deleted user') }} · {{ $change->created_at->diffForHumans() }}</span></li>@empty<li class="text-sm text-[#737a72]">{{ __('No changes recorded yet.') }}</li>@endforelse</ol></section>
</div>
